server:
  port: 8888
logging:
  level:
    root: INFO
    org.spring.framework.cloud.config: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bindian0509/spring-cloud-config-server-repository.git
          username: bindian0509
          password: ENC(MGtbPzWpQBzKaMkNOdUKY1jf+Ze/p8aPjs58AtXlJgd+xN59nC6bBvU9myolUPe1L240qhijFY/rWQJ2yMpyXACZppaGHazIgfVx1SzFjPlRL6Y5eC8ruoqPqEqBZ6jFEFXoblkTCMB5PImlR7GwBYD3/IH2dctk76qwB49345w=)
          default-label : master
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: ENC(isWgBV5UFp/JH450ZJIRwSScC96KxsDlErIvT+BCnPfT7ctKoZkAIudeviXGVN+3c+6Rpo8j45Z/PfZJMt+Ggg==)
jasypt:
  encryptor:
    password: Demo_Pwd!2023
